### ISSUE TITLE
Cannot add to HACS as a custom repository

### ISSUE THREAD

**Issue by 2wenty2wo** [IDmedia/hass-medusa#1]
Hi,

Adding `https://git.idmedia.no/home-assistant/hass-medusa` to HACS as a custom repository doesn't work, it doesn't error, it just doesn't do anything. Going to that link also asks me to log in.

Thanks 😊

![Screen Shot 2021-07-13 at 12 52 29 pm](https://user-images.githubusercontent.com/11643336/125382670-6e210c00-e3d9-11eb-93d5-548ca784fb9c.png)

**Comment by 2wenty2wo** [comment]
Worked it out, wrong URL.
It should be `https://github.com/IDmedia/hass-medusa.git`.
I've submitted a pull request. #2

**Comment by IDmedia** [comment]
Yeah, sorry my bad. The reason for that is that I put all my code in Gitlab and sync it to Github.
Just forgot to use the github url, but I fixed it now, thanks for letting me know. :)
