### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by annomatik** [IDmedia/hass-medusa#7]
Hi! I have just installed Home Assistant and can't seem to install the Medusa integration.

I go to
- Configuration --> Add-ons --> Add On Store,
- Click on the three dots to the top right,
- select "Repositories",
- enter "https://github.com/IDmedia/hass-medusa",
- press "Add" and get a
- "(!) Invalid Add-on repository!"

Please help, thank you!

![image](https://user-images.githubusercontent.com/28311452/160293463-aa8ab825-74cf-4df2-a0a9-be3d3fb41eb6.png)

**Comment by IDmedia** [comment]
Make sure to select "Category: Integration" and that the URL does not contain spaced of any kind. I've tested it on mulitiple instances and it works without issues: 
![image](https://user-images.githubusercontent.com/450724/186364006-a2e1f06d-f024-424d-9a8e-af70bb2ba759.png)
